config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  get 'homes/about'
  get 'homes/contact'
  get 'homes/music'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def music
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="background-image-about">
	<%= render 'layouts/header' %>
	<main>
		<h1 class="page-title center">ABOUT</h1>
		<div class="contents-box">
			<div class="center-box">
			    <div class="about-image"></div>
			    <h3>SUPER ORGANISM</h3>
			    <p>introductionintroductionintroductionintroductionint<br>
			    roductionintroductionintroductionintroductionintroductionintroduction</p>
		    </div>
		</div>
	</main>
	<%= render "layouts/footer"%>
</div>

app/views/homes/contact.html.erb
<div class="background-image-about">
	<%= render 'layouts/header' %>
	<main>
		<h1 class="page-title center">CONTACT</h1>
		  <div class="center-contact-box">
		  	<div class="contact-box">
		  	  <h4 class="inline">MAIL:</h2>
		  	  <p class="inline">EXAMPLE@EXAMPLE.COM
		  	 </div>
		  	<div class="contact-box">
		  	  <h4 class="inline">TELL:</h2>
		  	  <p class="inline">XXX-XXXX-XXXX</p>
		  	</div>
		  </div>
	</main>
	<%= render "layouts/footer"%>
</div>

app/views/homes/home.html.erb
<div class="background-image-home">
	<%= render 'layouts/header' %>
	<main>
		<div class="title-box">
			<h2>DSCVR</h2>
			<h1>SUPER ORGANISM</h1>
			<p>SOMETHING FPR YOUR M.I.N.D</p>
		</div>
	</main>
	<%= render 'layouts/footer'%>
</div>

app/views/homes/music.html.erb
<div class="background-image-about">
	<%= render 'layouts/header' %>
	<main>
		<h1 class="page-title center">MUSIC</h1>
		<div class="music-contents-box">
			<div class="box">
			<div class="music-box">
			    <div class="disc-image1"></div>
		    </div>
		    <div class="introduction">
		    	<h3 class="disc-name">A TOUR for YOUR M.I.N.D</h3>
		    	<ul class="disc-list">
		    	  <li>1.  music1</li>
		    	  <li>2.  music2</li>
		    	  <li>3.  music3</li>
		    	  <li>4.  music4</li>
		    	</ul>
		    </div>
		    </div>
		</div>
		<div class="music-contents-box">
			<div class="box">
			<div class="music-box">
			    <div class="disc-image2"></div>
		    </div>
		    <div class="introduction">
		    	<h3 class="disc-name">SUPER ORGANISM</h3>
		    	<ul class="disc-list">
		    	  <li>1.  music1</li>
		    	  <li>2.  music2</li>
		    	  <li>3.  music3</li>
		    	  <li>4.  music4</li>
		    	</ul>
		    </div>
		    </div>
		</div>
		<div class="music-contents-box">
			<div class="box">
			<div class="music-box">
			    <div class="disc-image3"></div>
		    </div>
		    <div class="introduction">
		    	<h3 class="disc-name">A TOUR for YOUR M.I.N.D</h3>
		    	<ul class="disc-list">
		    	  <li>1.  music1</li>
		    	  <li>2.  music2</li>
		    	  <li>3.  music3</li>
		    	  <li>4.  music4</li>
		    	</ul>
		    </div>
		    </div>
		</div>
		<div class="music-contents-box">
			<div class="box2">
			  <iframe width="560" height="315" src="https://www.youtube.com/embed/mJQYRzAoErc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		    </div>
		</div>
	</main>
	<%= render "layouts/footer"%>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<span class="footer-text">@copyright</span>
</footer>

app/views/layouts/_header.html.erb
<header class="container">
	<nav>
		<ul class="navigation">
			<li></li>
			<li><%= link_to "HOME",root_path %></li>
			<li></li>
			<li><%= link_to "ABOUT",homes_about_path %></li>
			<li></li>
			<li><%= link_to "MUSIC",homes_music_path %></li>
			<li></li>
			<li><%= link_to "CONTACT",homes_contact_path %></li>
			<li></li>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BandApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>